import fs from 'node:fs/promises';
import path from 'node:path';

const projectRoot = process.cwd();

const inputDir = path.join(projectRoot, 'public', 'blog');
const outputFile = path.join(
  projectRoot,
  'src',
  'app',
  'data',
  'blog-posts.generated.ts',
);

function isSlug(value) {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value);
}

function parseFrontmatter(raw) {
  const normalized = raw.replace(/\r\n/g, '\n');
  if (!normalized.startsWith('---\n')) {
    return { frontmatter: {}, body: raw };
  }

  const end = normalized.indexOf('\n---\n', 4);
  if (end === -1) {
    throw new Error('Frontmatter started but no closing --- found.');
  }

  const fmBlock = normalized.slice(4, end).trim();
  const body = normalized.slice(end + '\n---\n'.length).replace(/^\n+/, '');

  const frontmatter = {};
  for (const line of fmBlock.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const colonIndex = trimmed.indexOf(':');
    if (colonIndex === -1) continue;

    const key = trimmed.slice(0, colonIndex).trim();
    let value = trimmed.slice(colonIndex + 1).trim();

    // Basic array syntax: [a, b, c]
    if (value.startsWith('[') && value.endsWith(']')) {
      const inner = value.slice(1, -1).trim();
      const parts = inner
        ? inner.split(',').map((p) => p.trim()).filter(Boolean)
        : [];
      frontmatter[key] = parts;
      continue;
    }

    // Strip optional surrounding quotes
    value = value.replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
    frontmatter[key] = value;
  }

  return { frontmatter, body };
}

function escapeForTemplateLiteral(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

async function main() {
  let entries;
  try {
    entries = await fs.readdir(inputDir, { withFileTypes: true });
  } catch (err) {
    throw new Error(
      `Blog input folder not found: ${inputDir}. Create it and add .md files.`,
    );
  }

  const markdownFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith('.md'))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));

  const posts = [];

  for (const fileName of markdownFiles) {
    const slug = fileName.replace(/\.md$/, '');
    if (!isSlug(slug)) {
      throw new Error(
        `Invalid post filename: ${fileName}. Use kebab-case like my-first-post.md`,
      );
    }

    const fullPath = path.join(inputDir, fileName);
    const raw = await fs.readFile(fullPath, 'utf8');
    const { frontmatter, body } = parseFrontmatter(raw);

    const title = frontmatter.title;
    const date = frontmatter.date;

    if (!title || typeof title !== 'string') {
      throw new Error(`Missing required frontmatter 'title' in ${fileName}`);
    }

    if (!date || typeof date !== 'string') {
      throw new Error(`Missing required frontmatter 'date' in ${fileName}`);
    }

    const description =
      typeof frontmatter.description === 'string'
        ? frontmatter.description
        : '';

    const tags = Array.isArray(frontmatter.tags)
      ? frontmatter.tags
      : typeof frontmatter.tags === 'string' && frontmatter.tags
        ? frontmatter.tags
            .split(',')
            .map((t) => t.trim())
            .filter(Boolean)
        : [];

    posts.push({
      slug,
      title,
      date,
      description,
      tags,
      markdown: body,
    });
  }

  posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

  const ts = `/* eslint-disable */
// This file is auto-generated by scripts/generate-blog.mjs.
// Do not edit by hand.

export type BlogPostSource = {
  slug: string;
  title: string;
  date: string; // YYYY-MM-DD
  description: string;
  tags: string[];
  markdown: string;
};

export const blogPosts: BlogPostSource[] = [\n${posts
    .map((p) => {
      const markdown = escapeForTemplateLiteral(p.markdown);
      return `  {\n    slug: ${JSON.stringify(p.slug)},\n    title: ${JSON.stringify(
        p.title,
      )},\n    date: ${JSON.stringify(p.date)},\n    description: ${JSON.stringify(
        p.description,
      )},\n    tags: ${JSON.stringify(p.tags)},\n    markdown: \`${markdown}\`,\n  }`;
    })
    .join(',\n')}\n];\n`;

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, ts, 'utf8');

  console.log(`Generated ${outputFile} (${posts.length} posts)`);
}

await main();
