/* eslint-disable */
// This file is auto-generated by scripts/generate-blog.mjs.
// Do not edit by hand.

export type BlogPostSource = {
  slug: string;
  title: string;
  date: string; // YYYY-MM-DD
  description: string;
  tags: string[];
  markdown: string;
};

export const blogPosts: BlogPostSource[] = [
  {
    slug: "hello-world",
    title: "Hello, World!",
    date: "2026-01-16",
    description: "My first post on this portfolio site.",
    tags: ["angular","portfolio","personal"],
    markdown: `# Hello, World!

I’ve wanted a place on my own domain to write short notes about what I’m learning, what I’m building, and what I’m thinking about in tech.

<!-- ![Blog placeholder image](/images/blog/placeholder.svg) -->

This blog lives directly inside my Angular app, using Markdown files that get turned into routes at build time.

## What I’m optimizing for

- Owning my content
- Keeping it simple
- Great performance and SEO

Thanks for reading — more posts coming soon.
`,
  }
];
