/* eslint-disable */
// This file is auto-generated by scripts/generate-oss-stats.mjs.
// Do not edit by hand.

export type OssProject = {
  repo: string;
  url: string;
  stars: number;
  mergedPrs: number;
};

export type OssStats = {
  totalMergedPrs: number;
  projectCount: number;
  totalStars: number;
  updated: string; // YYYY-MM-DD
  projects: OssProject[];
};

export const ossStats: OssStats = {
  "totalMergedPrs": 5,
  "projectCount": 2,
  "totalStars": 21463,
  "updated": "2026-09-21",
  "projects": [
    {
      "repo": "BCUninstaller/Bulk-Crap-Uninstaller",
      "url": "https://github.com/BCUninstaller/Bulk-Crap-Uninstaller/pulls?q=is%3Apr%20author%3Ahazeliscoding%20is%3Amerged",
      "stars": 21453,
      "mergedPrs": 4
    },
    {
      "repo": "sjmh/pyqb",
      "url": "https://github.com/sjmh/pyqb/pulls?q=is%3Apr%20author%3Ahazeliscoding%20is%3Amerged",
      "stars": 10,
      "mergedPrs": 1
    }
  ]
};
